# 语义槽配置
semantic_slot = [
    {
        "question_type": "城市有什么学校",
        "keywords": ["有哪", '都有什么', '有什么', '那些', '哪些', '包含'],
        "slot_list": ["大学", '城市'],
        "sql": [
            "MATCH (m)<-[:`位于`]-(n:`大学`) where {} return m.name, n.name",
            "MATCH (m)-[]-(mm)<-[:`位于`]-(n:`大学`) where {} return m.name, n.name",
        ],
        "subject": "m.name",
        "object": ["n.name", ],
        "pretty": "{} 有 {}这些大学",
    },
    {
        "question_type": "学校的类别",
        "keywords": ['层次', '水平', '211', '985', '双一流'],
        "slot_list": ["大学"],
        "sql": "MATCH (m)-[:`属于`]->(n:`学校层次`) where {} return m.name, n.name",
        "subject": "m.name",
        "object": ["n.name", ],
        "pretty": "{} 属于 {}",
    },
    {
        "question_type": "包含",
        "keywords": ["有哪", '都有什么', '有什么', '那些', '哪些'],
        "slot_list": ["学校层次"],
        "sql": "MATCH (m)<-[:`属于`]-(n:`大学`) where {} return m.name, n.name",
        "subject": "m.name",
        "object": ["n.name", ],
        "pretty": "院校{} 包含 {}这些大学",
    },

    {
        "question_type": "简介",
        "keywords": ["简介", '概述'],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.desc",
        "subject": "m.name",
        "object": ["m.desc", ],
        "pretty": "{}: {}",
    },
    {
        "question_type": "主管部门",
        "keywords": ["主管"],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.`主管部门`",
        "subject": "m.name",
        "object": ["m.`主管部门`", ],
        "pretty": "{}的主管部门是{}",
    },
    {
        "question_type": "主要奖项",
        "keywords": ["主要奖项"],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.`主要奖项`",
        "subject": "m.name",
        "object": ["m.`主要奖项`", ],
        "pretty": "{}的主要奖项是{}",
    },
    {
        "question_type": "学校类别",
        "keywords": ["学校类别"],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.`学校类别`",
        "subject": "m.name",
        "object": ["m.`学校类别`", ],
        "pretty": "{}的学校类别是{}",
    },
    {
        "question_type": "学校特色",
        "keywords": ["特色"],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.`学校特色`",
        "subject": "m.name",
        "object": ["m.`学校特色`", ],
        "pretty": "{}的学校特色是{}",
    },
    {
        "question_type": "外文名",
        "keywords": ["外文名", '英文名'],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.`外文名`",
        "subject": "m.name",
        "object": ["m.`外文名`", ],
        "pretty": "{}的外文名是{}",
    },
    {
        "question_type": "办学性质",
        "keywords": ["民办", '性质', '公立', '私立'],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.`办学性质`",
        "subject": "m.name",
        "object": ["m.`办学性质`", ],
        "pretty": "{}的办学性质是{}",
    },
    {
        "question_type": "校歌",
        "keywords": ["校歌"],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.`校歌`",
        "subject": "m.name",
        "object": ["m.`校歌`", ],
        "pretty": "{}的校歌是{}",
    },
    {
        "question_type": "校训",
        "keywords": ["校训"],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.`校训`",
        "subject": "m.name",
        "object": ["m.`校训`", ],
        "pretty": "{}的校训是{}",
    },
    {
        "question_type": "院歌",
        "keywords": ["院歌"],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.`院歌`",
        "subject": "m.name",
        "object": ["m.`院歌`", ],
        "pretty": "{}的院歌是{}",
    },
    {
        "question_type": "院训",
        "keywords": ["院训"],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.`院训`",
        "subject": "m.name",
        "object": ["m.`院训`", ],
        "pretty": "{}的院训是{}",
    },
    {
        "question_type": "现任领导",
        "keywords": ["领导"],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.`现任领导`",
        "subject": "m.name",
        "object": ["m.`现任领导`", ],
        "pretty": "{}的现任领导是{}",
    },
{
        "question_type": "地址",
        "keywords": ["地址", '在哪'],
        "slot_list": ["大学"],
        "sql": "MATCH (m) where {} return m.name, m.`地址`",
        "subject": "m.name",
        "object": ["m.`地址`", ],
        "pretty": "{}的地址{}",
    },
]
